from enum import Enum

class MQConnackCode(Enum):
    MQ_ACCEPTED = 0,
    MQ_UNACCEPTABLE_PROTOCOL_VERSION = 1,
    MQ_IDENTIFIER_REJECTED = 2,
    MQ_SERVER_UNUVALIABLE = 3,
    MQ_BAD_USER_OR_PASS = 4,
    MQ_NOT_AUTHORIZED = 5