from enum import Enum

class ConnectionState(Enum):
    NONE = 0
    CHANNEL_CREATING = 1
    CHANNEL_ESTABLISHED = 2
    CHANNEL_FAILED = 3
    CONNECTING = 4
    CONNECTION_ESTABLISHED = 5
    CONNECTION_FAILED = 6
    CONNECTION_LOST = 7